apps/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth.views import LogoutView
from apps.users.views import RegisterationView, \
    CompleteProfile, LoginView, \
    DashboardView, \
    AddItemsView, EditProfileView, MonthlyCalories, Home, CaloriesByWeekView, Search

app_name = 'users'

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("login/", LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("register/", RegisterationView.as_view(), name="registration"),
    path("create/profile/", CompleteProfile.as_view(), name="create_profile"),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('add/items/', AddItemsView.as_view(), name="add_food"),
    path('profile/edit/', EditProfileView.as_view(), name="edit_profile"),
    path('monthly/', MonthlyCalories.as_view(), name="monthly_calories"),
    path("week/<int:year>/<int:week>/", CaloriesByWeekView.as_view(), name="week"),
    path('search/', Search.as_view(), name="search")
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls'))

]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/users/models.py
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel

from apps.users.managers import UserManager

# Create your models here.


class User(TimeStampedModel, AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


class Profile(TimeStampedModel):
    class Gender(models.TextChoices):
        Male = 'male', 'Male'
        Female = 'female', 'Female'
        Other = 'other', 'Other'

    class Question(models.TextChoices):
        GAIN = 'gain', 'Gain'
        LOSE = 'lose', 'Lose'

    class LifeStyle(models.TextChoices):
        Sedentary = 'sedentary', 'Sedentary'
        Lightly_Active = 'lightly_active', 'Lightly Active'
        Moderately_Active = 'moderately_active', 'Moderately Active'
        Very_Active = 'very_active', 'Very Active'
        Extra_Active = 'extra_active', 'Extra Active'

    user = models.OneToOneField(to=get_user_model(), related_name="profile", on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=Gender.choices, default='', null=True, blank=True)
    life_style = models.CharField(max_length=20, choices=LifeStyle.choices, default='', null=True, blank=True)
    height = models.FloatField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    dob = models.DateField(_('data of birth'), null=True)
    question = models.CharField(max_length=10, choices=Question.choices, blank=True, null=True)
    is_profile_complete = models.BooleanField(null=True, blank=True, default=False)

    def get_life_style(self):
        return self.life_style.replace("_", ' ')

    def get_age(self):
        return timezone.now().year - self.dob.year

    def get_height_in_centimeter(self):
        return self.height

    def get_bmr(self):
        multiply = {
            'sedentary': 1.2,
            'lightly_active': 1.375,
            'moderately_active': 1.55,
            'very_active': 1.725,
            'extra_active': 1.9
        }

        bmr = (10 * self.weight) + (6.25 * self.get_height_in_centimeter()) - (5 * self.get_age()) 
        bmr = bmr + 5 if self.gender == self.Gender.Male.value else bmr - 161

        bmr *= multiply[self.life_style]

        return round(bmr)


class FoodItem(TimeStampedModel):
    class ConsumedAtChoices(models.TextChoices):
        Lunch = 'lunch', 'Lunch'
        Dinner = "dinner", 'Dinner'
        Break_Fast = 'break_fast', 'Break Fast'

    name = models.CharField(max_length=100)
    calories = models.FloatField()
    consumed_at = models.CharField(max_length=12, choices=ConsumedAtChoices.choices)

    user = models.ForeignKey(to=get_user_model(), related_name='foods', on_delete=models.CASCADE, null=True)

    def get_consumed_at(self):
        return self.consumed_at.replace('_', ' ')

apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()


class RegisterForm(forms.ModelForm):
    """
    The default

    """

    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean_email(self):
        '''
        Verify email is available.
        '''
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ['email', 'password', 'is_active']

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

apps/users/views.py
import calendar
from collections import Counter
from django.db.models import Sum
from django.utils import timezone
from django.http import JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from django.views.generic import CreateView
from django.contrib.auth import get_user_model

from apps.users.models import Profile, FoodItem

User = get_user_model()

class Home(View):
    def get(self, request):
        return redirect("users:dashboard")

class RegisterationView(View):

    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        data = request.POST
        if data.get("password") == data.get("confirm_password"):
            user = User.objects.create(
                email=data.get("email"),
                first_name=data.get("first_name"),
                last_name=data.get("last_name")
            )
            user.set_password(data.get("password"))
            user.save()
            Profile.objects.create(user=user)
            user = authenticate(email=data.get("email"), password=data.get("password"))
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 message="Account Created Successfully! Please complete your profile")

            return redirect("users:create_profile")

        messages.add_message(request, messages.ERROR, message="Check your email and password")
        return render(request, "register.html")


class CompleteProfile(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        if user.profile.is_profile_complete:
            return redirect("users:dashboard")
        return render(request, 'create_profile.html')


    def post(self, request):
        data = request.POST
        profile = request.user.profile
        profile.gender = data.get("gender")
        profile.life_style = data.get("life_style")
        profile.height = data.get("height")
        profile.weight = data.get("weight")
        profile.dob = data.get("dob")
        profile.question = data.get("question")
        profile.is_profile_complete = True
        profile.save()
        return redirect("users:dashboard")


class LoginView(View):
    def get(self, request):
        user = request.user
        if user.is_authenticated:
            return redirect('users:dashboard')
        return render(request, 'login.html')

    def post(self, request):
        data = request.POST
        user = User.objects.get(email=data.get("email"))
        if user.check_password(data.get("password")):
            user = authenticate(email=data.get("email"), password=data.get("password"))
            login(request, user)
            return redirect("users:dashboard")
        return redirect("users:login")


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        if user.is_superuser:
            return redirect(to='/admin')
        if user.profile.is_profile_complete:
            today_calories = user.foods.filter(created__date=timezone.now().date()).aggregate(calories=Sum('calories'))['calories']
            if today_calories:
                if today_calories > user.profile.get_bmr():
                    messages.add_message(request, messages.WARNING, "You have to take less calories to reduce your weight")
            else:
                messages.add_message(request, messages.WARNING, "You have to take more calories to increase your weight")

            context = {
                'today_calories': today_calories if today_calories else 0,

            }
            return render(request, 'dashboard.html', context)
        return redirect("users:create_profile")


class AddItemsView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'add_items.html')

    def post(self, request):
        user = request.user
        data = request.POST

        food_name = data.getlist('food')
        calories = data.getlist('calories')
        time = data.getlist('time')
        food_items = []
        for item_index in range(0, len(food_name)):
            food_item = FoodItem(user=user, name=food_name[item_index], calories=calories[item_index],
                                 consumed_at=time[item_index])
            food_items.append(food_item)
        FoodItem.objects.bulk_create(food_items)

        return render(request, 'add_items.html')


class EditProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "edit_profile.html")

    def post(self, request):
        user = request.user
        data = request.POST

        user.first_name = data.get("first_name")
        user.last_name = data.get("last_name")
        user.save()

        user.profile.height = data.get("height")
        user.profile.weight = data.get("weight")
        user.profile.gender = data.get("gender")
        user.profile.life_style = data.get("life_style")
        user.profile.dob = data.get("dob")
        user.profile.question = data.get("question")
        user.profile.save()
        return redirect('users:dashboard')


class MonthlyCalories(View):
    def post(self, request):
        fooditem_days = {}

        user = request.user
        month = int(request.POST["month"]) + 1
        year = int(request.POST["year"])
        month_name = calendar.month_name[month]
        _, month_len = calendar.monthrange(year=year, month=month)

        days = [day for day in range(1, month_len + 1)]
        food_items = FoodItem.objects.filter(user=user, created__month=month, created__year=year)
        for food_item in food_items:
            if fooditem_days.get(food_item.created.day):
                fooditem_days[food_item.created.day] += food_item.calories
            else:
                fooditem_days[food_item.created.day] = food_item.calories

        monthly_calories = {}
        for day in days:
            if fooditem_days.get(day):
                monthly_calories[day] = fooditem_days[day]
            else:
                monthly_calories[day] = 0

        data = {
            "days": list(monthly_calories.keys()),
            "calories": list(monthly_calories.values())
        }

        return JsonResponse(data)


class CaloriesByWeekView(View):
    def get(self, request, year, week):
        user = request.user
        calories = 0
        for food in user.foods.filter(created__week=week, created__year=year):
            calories += food.calories
        context = {
            'calories': calories
        }
        return JsonResponse(context)


class Search(LoginRequiredMixin, View):
    template = "search.html"

    def get(self, request, *args, **kwargs):
        user = request.user
        context = {}
        data = request.GET
        date = data.get('date')
        week = data.get('week')
        day = data.get('day')
        item_key = 'items'
        if data:
            context[item_key] = user.foods.filter(created__date=date)
        if week:
            year, week = week.split('-W')
            context[item_key] = user.foods.filter(created__week=week, created__year=year)
        if day and int(day) in list(range(1, 32)):
            context[item_key] = user.foods.filter(created__date__day=day)

        return render(request, self.template, context=context)

apps/users/templates/add_items.html
{% extends 'base.html' %}
{% block content %}
    <div class="addfood-form">
        <div class="col-12 p-5">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                <div class="fooditems">
                    <div class="row">
                        <div class="col-3">
                            <div class="mb-3">
                                <label for="food_name" class="form-label">Food Name</label>
                                <input type="text" class="form-control" id="food_name" name="food" required>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="mb-3">
                                <label for="calories" class="form-label">Calories</label>
                                <input type="number" class="form-control" id="calories" name="calories" required>
                            </div>
                        </div>
                        <div class="col-3">
                            <label for="time" class="form-label">Food Time</label>
                            <select class="form-select" name="time" id="time" aria-label="Default select example" required>
                                <option selected disabled>Chose...</option>
                                <option value="lunch">Lunch</option>
                                <option value="dinner">Dinner</option>
                                <option value="break_fast">Break Fast</option>
                            </select>
                        </div>
                    </div>

                </div>
                <button type="button" class="btn btn-primary add-food">Add More</button>
                <div class="col-3 mt-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/users/templates/create_profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="authform">
        <div class="col-4 box p-5">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="gender" class="form-label">Gender</label>
                            <select class="form-select" name="gender" aria-label="Default select example" required>
                                {% comment %} <option selected disabled>Gender</option> {% endcomment %}
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="life_style" class="form-label">Life Style</label>
                            <select class="form-select" name="life_style" aria-label="Default select example" required>
                                {% comment %} <option selected disabled>LifeStyle</option> {% endcomment %}
                                <option value="sedentary">Sedentary</option>
                                <option value="lightly_active">Lightly Active</option>
                                <option value="moderately_active">Moderately Active</option>
                                <option value="very_active">Very Active</option>
                                <option value="extra_active">Extra Active</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="height" class="form-label">Height</label>
                            <input type="height" class="form-control" id="height" name="height" placeholder="cm"
                            required>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            <label for="weight" class="form-label">Weight</label>
                            <input type="number" class="form-control" id="weight" name="weight" 
                            placeholder="kg"
                            required>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="dob" class="form-label">Date of Birth</label>
                    <input type="date" class="form-control" id="dob" name="dob" required>
                </div>
                <div class="mb-3">
                    <label for="question">DO you want to lose or gain</label>
                    <select class="form-select" name="question" aria-label="Default select example" required>
                        <option selected disabled>chose</option>
                        <option value="gain">Gain</option>
                        <option value="lose">Lose</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Done</button>
            </form>
        </div>
    </div>
{% endblock %}

apps/users/templates/dashboard.html
{% extends 'base.html' %} {% block content %} {% csrf_token %}
<div class="row mt-4 ms-4">
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  <div class="col-7">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food Name</th>
          <th scope="col">Calories</th>
          <th scope="col">Time</th>
        </tr>
      </thead>
      <tbody>
        {% for food in user.foods.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ food.name|capfirst }}</td>
          <td>{{ food.calories }}</td>
          <td>{{ food.get_consumed_at|title }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-5">
    <div class="border">
      <h2 class="text-center mt-2 p-3">{{ user.get_full_name|title }}</h2>
      <div class="row">
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >Gender</span
          >
          <span class="d-inline-block m-2 p-1"
            >{{ user.profile.gender|capfirst }}</span
          >
        </div>
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >Date of Birth</span
          >
          <span class="d-inline-block m-2 p-1">{{ user.profile.dob }}</span>
        </div>
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >Height</span
          >
          <span class="d-inline-block m-2 p-1">{{ user.profile.height }}</span>
        </div>
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >Weight</span
          >
          <span class="d-inline-block m-2 p-1">{{ user.profile.weight }}</span>
        </div>
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >Life Style</span
          >
          <span class="d-inline-block m-2 p-1"
            >{{ user.profile.get_life_style|title }}</span
          >
        </div>
        <div class="col-6 d-flex justify-content-between">
          <span class="profile-info d-inline-block m-2 p-2 bg-dark rounded-3"
            >BMR</span
          >
          <span class="d-inline-block m-2 p-1">{{ user.profile.get_bmr }}</span>
        </div>
      </div>
      <div class="row">
        <div class="col-4 ms-2 mb-2 mt-2">
          <a href="{% url 'users:edit_profile' %}" class="btn btn-primary"
            >Edit</a
          >
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mt-4 ms-4">
  <div class="col-4">
    <h2>Today Calories : {{ today_calories }}</h2>
  </div>
</div>
{#<div class="row mt-4 ms-4">#}
{#  <div class="col-3">Select Week : <input type="week" /></div>#}
{#  <div class="col-6">#}
{#    <h4 class="weekly_calories">Select week to see calories</h4>#}
{#  </div>#}
{#</div>#}
<div class="row mt-4 ms-4">
  <div class="col-8">
    <!-- tabs for months -->
    <div class="tab-wrapper">
      <div class="tabs">
        <div class="left">
          <button type="button">&lt;</button>
        </div>
        <div class="month" data-month-index="0">Jan</div>
        <div class="right">
          <button type="button">&gt;</button>
        </div>
      </div>
    </div>
    <!-- ended -->
    <div>
      <canvas id="myChart"></canvas>
    </div>
  </div>
</div>
{% endblock %}

apps/users/templates/login.html
{% extends 'base.html' %}
    
{% block content %}
<style>
    body{
    font-family: Helvetica;
    background-color: #F0F2F5;
    background-image: url(img/calc1.jpg);
    background-size: cover;
    
    }
    #logo-container{
        float: left;
        margin-top: 165px;
        margin-left: 70px;
        width: 520px;
    }
    #logo-container p{
        font-size: 25px;
        font-weight: bold;
        margin-top: 0px;
        padding-left: 28px; 
    }
    .logo{
        width: 100px;
        height: 100px;
    }
    .logo img{
        width: 500px;
        height: 200;
        margin-top: -140px;
        margin-left: -75px;
    }
    #form-contaioner{
        float: right;
        width: 400px;
        margin-top: 125px;
        margin-right: 200px;
    }
    .form{
        border: 1px solid none;
        padding: 5px 18px;
        background-color: #f0f0f8;
        border-radius: 10px;
        box-shadow: 0px 0px 5px #29293b80;
    }
    .form input{
        padding: 15px;
        margin-top: 15px;
        width: 330px;
        border: 1px solid #DDDFE2;
        background-color: white;
        border-radius: 10px;
        font-size: 17px;
    }
    .form input:focus{
        outline: none;
        border:1px solid #1877F2;
    }
    .login-button{
        padding: 12px;
        margin-top: 15px;
        margin-bottom: 15px;
        width: 363px;
        border-radius: 10px;
        border: 1px solid white;
        background-color: #2277e7;
        font-size: 20px;
        color: white;
        font-weight: bold;
    }
    .login-button:hover{
        background-color: #166FE5;
    }
    #forget-pass{    
        margin-left: 116px;
        text-decoration: none;
        color: #1840f2;
        font-size: 16px;
    }
    #forget-pass:hover{    
        margin-left: 116px;
        text-decoration: underline;
        font-size: 16px;
    }
    .form a:hover{
        text-decoration: underline;
    }
    hr{
        margin-top: 20px;
        border-top: 0.5px solid #afb8c4
    }
    .create_account-button{
        padding: 15px;
        margin-top: 15px;
        margin-left: 80px;
        margin-bottom: 18px;
        width: 199px;
        border-radius: 10px;
        border: 1px solid white;
        background-color: #17bb2d;
        font-size: 17px;
        color: white;
        font-weight: bold;
    }
    .create_account-button:hover{
        background-color: #639357;
    }
    .create_page-para{
        margin-top: 28px;
        margin-left: 44px;
        font-size: 15px;
    }
    .create_page-para a{
        text-decoration: none;
        color: black;
        font-weight: bold;
    }
    .create_page-para a:hover{
        text-decoration: underline;
    }

</style>

    <div id="logo-container">
        <div class="logo">
            {% load static %}
            <img src="{% static 'img/Cal-03.png' %}" alt="caloreis calculator">

        </div>
        <div>
            <p>
                Calories Calculator helps you to track your daily
                calories.
            </p>
        </div>
    </div>
    <div id="form-contaioner">
        {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% endif %}
        <div class="form">
            <form method="post">
                {% csrf_token %}

                <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp"  placeholder="Email address" required >

                <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password" required>

                <button type="submit" class="login-button">Log In</button>
                <hr/>
                <a href="{% url 'users:registration' %}">
                    <button type="button" class="create_account-button"> Create New Account</button>
                </a>
            </form>
        </div>
    </div>

{% endblock %}

apps/users/templates/search.html
{% extends 'base.html' %} {% block content %} {% csrf_token %}
    <div class="row mt-4 ms-4">
        <div class="col-8">
            <div class="row mt-4 ms-4">
                <div class=" col-4">
                <form action="{% url 'users:search' %}">

                    <div class="col-3">
                        Date : <input type="date" name="date"/>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Search</button>
                </form>
                </div>
            <!-- </div> -->

            <!-- <div class="row mt-4 ms-4"> -->
                <div class=" col-4">

                <form action="{% url 'users:search' %}">

                    <div class="col-3">
                        Week : <input type="week" name="week"/>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Search</button>
                </form>
                </div>
            <!-- </div> -->

            <!-- <div class="row mt-4 ms-4"> -->
                <div class=" col-4">

                <form action="{% url 'users:search' %}">

                    <div class="col-3">
                        Day : <input type="number" min="1" max="31" step="1" name="day"/>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Search</button>
                </form>
                </div>
            </div>
        </div>
        <div class="col-7 mt-4 ml-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Food Name</th>
                    <th scope="col">Calories</th>
                    <th scope="col">Time</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>
                <tbody>
                {% for item in items %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.name|capfirst }}</td>
                        <td>{{ item.calories }}</td>
                        <td>{{ item.get_consumed_at|title }}</td>
                        <td>{{ item.created|date:'M d, Y' }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}